services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    command:
      - "--config=/etc/otel-collector.yaml"
      - "--config=/etc/otel-collector-config-extras.yaml"
    volumes:
      - ./config/otel-collector-default.yaml:/etc/otel-collector.yaml
      - ./config/otel-collector-config-extras.yaml:/etc/otel-collector-config-extras.yaml
    ports:
      - "3317:4317"   # OTLP GRPC
      - "4318:4318"   # OTLP HTTP
